[package]
name = "listener"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive", "env"] }
color-eyre = "0.6.5"
dotenvy = { version = "0.15.7", features = ["clap"] }
env_logger = "0.11.8"
eyre = "0.6.12"
log = "0.4.29"
rocket = "0.5.1"
